
import java.io.IOException;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.Scanner;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Marwan
 */
public class ClientChat extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClientChat.class.getName());
    private final String clientName;

    /**
     * Creates new form ClientChat
     *
     * @param userName
     */
    public ClientChat(String userName) {
        this.clientName = userName;
        initComponents();
        setTitle("Client - " + clientName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaChat = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaMessage = new javax.swing.JTextArea();
        jButtonSend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client");
        addPropertyChangeListener(this::formPropertyChange);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        jTextAreaChat.setColumns(20);
        jTextAreaChat.setRows(5);
        jScrollPane1.setViewportView(jTextAreaChat);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTextAreaMessage.setColumns(20);
        jTextAreaMessage.setRows(5);
        jTextAreaMessage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextAreaMessageKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTextAreaMessage);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jButtonSend.setText("Send");
        jButtonSend.addActionListener(this::jButtonSendActionPerformed);
        jPanel1.add(jButtonSend, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        setSize(new java.awt.Dimension(565, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        // TODO add your handling code here:
        String message = jTextAreaMessage.getText().trim();
        if (message.startsWith("@")) {
            commandHandler(message);
            jTextAreaMessage.setText("");
        } else {
            writer.println(clientName + ": " + message);
            writer.flush();
            jTextAreaChat.append("Me: " + message + "\n");
            jTextAreaMessage.setText("");
        }
    }

    private void commandHandler(String command) {
        switch (command.toLowerCase()) {
            case "@exit":
                jTextAreaChat.append("close system........\n");
                System.exit(0);
                break;

            case "@clear":
                jTextAreaChat.setText("");
                break;

            case "@all":
                StringBuilder sb = new StringBuilder();
                sb.append("*** Online Clients (").append(clientNames.size()).append(") ***\n");
                synchronized (clientNames) {
                    for (String name : clientNames) {
                        sb.append("  - ").append(name).append("\n");
                    }
                }
                jTextAreaChat.append(sb.toString());
                break;

            case "@help":
                jTextAreaChat.append("""
                                     \n
                                         ***************************************
                                         *  @clear: Clear Chat                 * 
                                         *  @help : Show all commands          *
                                         *  @exit : exit program               *
                                         *  @all  : show all connected users   *
                                         ***************************************\n
                                         """);
                break;
            default:
                jTextAreaChat.append("*** undefined command: " + command + " ***\n");
                break;
        }
    }//GEN-LAST:event_jButtonSendActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Thread connectioThread = new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    try {
                        socket = new Socket("localhost", 20597);
                        scanner = new Scanner(socket.getInputStream());
                        writer = new PrintWriter(socket.getOutputStream(), true);

                        writer.println("*** " + clientName + " has joined the chat ***");
                        writer.flush();

                        javax.swing.SwingUtilities.invokeLater(() -> {
                            jTextAreaChat.append("*** Connected to server ***\n");
                            jButtonSend.setEnabled(true);
                        });

                        while (true) {
                            String message = scanner.nextLine();
                            javax.swing.SwingUtilities.invokeLater(() -> {
                                jTextAreaChat.append(message + "\n");
                            });
                        }

                    } catch (IOException ex) {
                        if (writer != null) {
                            writer.println("*** " + clientName + " has left the chat ***");
                            writer.flush();
                        }

                        javax.swing.SwingUtilities.invokeLater(() -> {
                            jTextAreaChat.append("*** Server is not running, retrying... ***\n");
                            jButtonSend.setEnabled(false);
                        });

                        try {
                            Thread.sleep(3000);
                        } catch (InterruptedException e) {
                            Thread.currentThread().interrupt();
                            break;
                        }
                    }
                }
            }
        });
        connectioThread.setDaemon(true);
        connectioThread.start();
    }//GEN-LAST:event_formWindowOpened

    private void jTextAreaMessageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaMessageKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            evt.consume();
            jButtonSend.doClick();
        }
    }//GEN-LAST:event_jTextAreaMessageKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSend;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaChat;
    private javax.swing.JTextArea jTextAreaMessage;
    // End of variables declaration//GEN-END:variables
    private Socket socket;
    private Scanner scanner;
    private PrintWriter writer;
    
    private java.util.List<PrintWriter> clients = new java.util.ArrayList<>();
    private java.util.List<String> clientNames = new java.util.ArrayList<>();
}
