/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Marwan
 */
public class LogIn extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LogIn.class.getName());

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passwordjPasswordField = new javax.swing.JPasswordField();
        userNamejTextField = new javax.swing.JTextField();
        logInjButton = new javax.swing.JButton();
        ExitjButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        logInjButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(350, 200));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user1.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 50, 210, 210);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Log in");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(380, 0, 110, 70);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(290, 120, 123, 32);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("User Name:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(290, 80, 123, 32);
        jPanel1.add(passwordjPasswordField);
        passwordjPasswordField.setBounds(420, 130, 250, 22);

        userNamejTextField.addActionListener(this::userNamejTextFieldActionPerformed);
        jPanel1.add(userNamejTextField);
        userNamejTextField.setBounds(420, 90, 250, 22);

        logInjButton.setBackground(new java.awt.Color(204, 204, 204));
        logInjButton.setText("Sign up");
        logInjButton.addActionListener(this::logInjButtonActionPerformed);
        jPanel1.add(logInjButton);
        logInjButton.setBounds(290, 220, 380, 20);

        ExitjButton.setBackground(new java.awt.Color(204, 0, 0));
        ExitjButton.setText("Exit");
        ExitjButton.addActionListener(this::ExitjButtonActionPerformed);
        jPanel1.add(ExitjButton);
        ExitjButton.setBounds(290, 270, 380, 23);

        jLabel5.setText("Or");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(470, 250, 20, 16);

        logInjButton1.setBackground(new java.awt.Color(204, 204, 204));
        logInjButton1.setText("Login");
        logInjButton1.addActionListener(this::logInjButton1ActionPerformed);
        jPanel1.add(logInjButton1);
        logInjButton1.setBounds(290, 170, 380, 23);

        jLabel6.setText("I dont have account");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(290, 200, 110, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(701, 337));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNamejTextFieldActionPerformed

    private void logInjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logInjButtonActionPerformed

    private void ExitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitjButtonActionPerformed

    private void logInjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInjButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logInjButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LogIn().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logInjButton;
    private javax.swing.JButton logInjButton1;
    private javax.swing.JPasswordField passwordjPasswordField;
    private javax.swing.JTextField userNamejTextField;
    // End of variables declaration//GEN-END:variables
}
