
import java.io.IOException;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.Scanner;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Marwan
 */
public class ServerChat extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ServerChat.class.getName());

    public ServerChat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaChat = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaMessage = new javax.swing.JTextArea();
        jButtonSend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server");
        addPropertyChangeListener(this::formPropertyChange);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        jTextAreaChat.setColumns(20);
        jTextAreaChat.setRows(5);
        jScrollPane1.setViewportView(jTextAreaChat);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTextAreaMessage.setColumns(20);
        jTextAreaMessage.setRows(5);
        jTextAreaMessage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextAreaMessageKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTextAreaMessage);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jButtonSend.setText("Send");
        jButtonSend.addActionListener(this::jButtonSendActionPerformed);
        jPanel1.add(jButtonSend, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        setSize(new java.awt.Dimension(565, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        // TODO add your handling code here:
        String message = jTextAreaMessage.getText().trim();
        if (message.startsWith("@")) {
            commandHandler(message);
            jTextAreaMessage.setText("");
        } else {
            synchronized (clients) {
                for (PrintWriter client : clients.keySet()) {
                    client.println("Server: " + message);
                    client.flush();
                }
            }
            jTextAreaChat.append("Me: " + message + "\n");
            jTextAreaMessage.setText("");
        }
    }//GEN-LAST:event_jButtonSendActionPerformed

    private void commandHandler(String command) {
        switch (command.toLowerCase()) {
            case "@exit":
                jTextAreaChat.append("close system........\n");
                System.exit(0);
                break;

            case "@clear":
                jTextAreaChat.setText("");
                break;

            case "@all":
                StringBuilder sb = new StringBuilder();
                synchronized (clients) {
                    sb.append("*** Online Clients (" + clients.size() + ") ***\n");
                    for (String name : clients.values()) {
                        sb.append("  - " + name + "\n");
                    }
                }
                jTextAreaChat.append(sb.toString());
                break;

            case "@help":
                jTextAreaChat.append("""
                                         \n
                                         ***************************************
                                         *  @clear: Clear Chat                 * 
                                         *  @help : Show all commands          *
                                         *  @exit : exit program               *
                                         *  @all  : show all connected users   *
                                         ***************************************
                                         \n
                                         """);
                break;
            default:
                jTextAreaChat.append("*** undefined command: " + command + " ***\n");
                break;
        }
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Thread serverThread = new Thread(() -> {
            try {
                serverSocket = new ServerSocket(20597);
                javax.swing.SwingUtilities.invokeLater(() -> jTextAreaChat.append("*** Server Started ***\n"));

                while (true) {
                    Socket clientSocket = serverSocket.accept();

                    Thread clientThread = new Thread(() -> {
                        PrintWriter clientWriter = null;
                        try {
                            Scanner clientScanner = new Scanner(clientSocket.getInputStream());
                            PrintWriter cw = new PrintWriter(clientSocket.getOutputStream(), true);
                            clientWriter = cw;

                            synchronized (clients) {
                                clients.put(cw, "Unknown");
                            }

                            while (clientScanner.hasNextLine()) {
                                String message = clientScanner.nextLine();

                                if (message.startsWith("@msg:")) {
                                    String[] parts = message.split(":", 4);
                                    if (parts.length == 4) {
                                        String target = parts[1].trim();
                                        String sender = parts[2].trim();
                                        String msg = parts[3].trim();

                                        synchronized (clients) {
                                            for (java.util.Map.Entry<PrintWriter, String> entry : clients.entrySet()) {
                                                if (entry.getValue().equals(target)) {
                                                    entry.getKey().println("[Private] " + sender + ": " + msg);
                                                    entry.getKey().flush();
                                                    break;
                                                }
                                            }
                                        }

                                        javax.swing.SwingUtilities.invokeLater(() -> jTextAreaChat.append("[Private] " + sender + " → " + target + "\n"));
                                        continue;
                                    }
                                }

                                if (message.startsWith("@all:")) {
                                    String requester = message.replace("@all:", "").trim();
                                    StringBuilder sb = new StringBuilder();
                                    synchronized (clients) {
                                        sb.append("*** Online Clients (" + clients.size() + ") ***\n");
                                        for (java.util.Map.Entry<PrintWriter, String> entry : clients.entrySet()) {
                                            if (entry.getValue().equals(requester)) {
                                                sb.append("  - " + entry.getValue() + " (You)\n");
                                            } else {
                                                sb.append("  - " + entry.getValue() + "\n");
                                            }
                                        }
                                    }
                                    cw.println(sb.toString());
                                    cw.flush();
                                    continue;
                                }

                                if (message.startsWith("*** ") && message.contains(" has joined")) {
                                    String name = message.replace("*** ", "").replace(" has joined the chat ***", "").trim();
                                    synchronized (clients) {
                                        clients.put(cw, name);
                                    }
                                }

                                javax.swing.SwingUtilities.invokeLater(()
                                        -> jTextAreaChat.append(message + "\n"));
                                broadcast(message, cw);
                            }

                        } catch (IOException ex) {
                        } finally {
                            if (clientWriter != null) {
                                synchronized (clients) {
                                    clients.remove(clientWriter);
                                }
                            }

                            try {
                                clientSocket.close();
                            } catch (IOException e) {
                            }
                        }
                    });
                    clientThread.setDaemon(true);
                    clientThread.start();
                }

            } catch (IOException ex) {
                javax.swing.SwingUtilities.invokeLater(()
                        -> jTextAreaChat.append("*** Server Error ***\n"));
            }
        });
        serverThread.setDaemon(true);
        serverThread.start();
    }

    private void broadcast(String message, PrintWriter sender) {
        synchronized (clients) {
            for (PrintWriter client : clients.keySet()) {
                if (client != sender) {
                    client.println(message);
                    client.flush();
                }
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void jTextAreaMessageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaMessageKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            evt.consume();
            jButtonSend.doClick();
        }
    }//GEN-LAST:event_jTextAreaMessageKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSend;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaChat;
    private javax.swing.JTextArea jTextAreaMessage;
    // End of variables declaration//GEN-END:variables
    private ServerSocket serverSocket;

    private java.util.Map<PrintWriter, String> clients = new java.util.LinkedHashMap<>();
}
