
import java.io.FileNotFoundException;
import java.io.IOException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Marwan
 */
public class SignUp extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignUp.class.getName());

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userNamejLabel = new javax.swing.JLabel();
        passwordjLabel = new javax.swing.JLabel();
        passwordjLabel1 = new javax.swing.JLabel();
        userNamejTextField = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jPasswordConfirmField = new javax.swing.JPasswordField();
        jshowPasswordCheckBox = new javax.swing.JCheckBox();
        logInjButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        signUpjButton = new javax.swing.JButton();
        ExitjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\BATU\\3rd\\semester 2\\Network Programming\\project\\Client-Server_Real-Time_Chat_Application\\assets\\user (2).png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Sign Up");

        userNamejLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userNamejLabel.setText("User Name:");

        passwordjLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        passwordjLabel.setText("Confirm Password:");

        passwordjLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        passwordjLabel1.setText("Password:");

        jshowPasswordCheckBox.setText("Show Password");
        jshowPasswordCheckBox.addActionListener(this::jshowPasswordCheckBoxActionPerformed);

        logInjButton1.setBackground(new java.awt.Color(204, 204, 204));
        logInjButton1.setText("Log In");
        logInjButton1.addActionListener(this::logInjButton1ActionPerformed);

        jLabel5.setText("Already have an account");

        signUpjButton.setBackground(new java.awt.Color(0, 102, 255));
        signUpjButton.setText("Sign Up");
        signUpjButton.addActionListener(this::signUpjButtonActionPerformed);

        ExitjButton.setBackground(new java.awt.Color(255, 0, 51));
        ExitjButton.setText("Exit");
        ExitjButton.addActionListener(this::ExitjButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jshowPasswordCheckBox)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(userNamejLabel)
                                                .addComponent(passwordjLabel1))
                                            .addGap(81, 81, 81)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(userNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(passwordjLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jPasswordConfirmField, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(375, 375, 375))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(signUpjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(logInjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ExitjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userNamejLabel)
                            .addComponent(userNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordjLabel1)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordjLabel)
                            .addComponent(jPasswordConfirmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jshowPasswordCheckBox)
                        .addGap(16, 16, 16)
                        .addComponent(signUpjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logInjButton1)
                        .addGap(15, 15, 15)
                        .addComponent(ExitjButton)
                        .addContainerGap(31, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jshowPasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jshowPasswordCheckBoxActionPerformed
        // TODO add your handling code here:
        if (jshowPasswordCheckBox.isSelected()) {
            jPasswordField.setEchoChar((char) 0);
            jPasswordConfirmField.setEchoChar((char) 0);
        } else {
            jPasswordField.setEchoChar('*');
            jPasswordConfirmField.setEchoChar('*');
        }
    }//GEN-LAST:event_jshowPasswordCheckBoxActionPerformed

    private void logInjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInjButton1ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logInjButton1ActionPerformed

    private void ExitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitjButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitjButtonActionPerformed

    private void signUpjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpjButtonActionPerformed
        // TODO add your handling code here:
        String userName = userNamejTextField.getText().trim();
        String password = new String(jPasswordField.getPassword()).trim();
        String confirm = new String(jPasswordConfirmField.getPassword()).trim();

        if (userName.isEmpty() || password.isEmpty() || confirm.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill all fields!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!password.equals(confirm)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Passwords do not match!", "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            jPasswordConfirmField.setText("");
            return;
        }

        if (isUserExists(userName)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Username already exists!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        saveUser(userName, password);

        javax.swing.JOptionPane.showMessageDialog(this, "Account created! You can now login.", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signUpjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignUp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordConfirmField;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JCheckBox jshowPasswordCheckBox;
    private javax.swing.JButton logInjButton1;
    private javax.swing.JLabel passwordjLabel;
    private javax.swing.JLabel passwordjLabel1;
    private javax.swing.JButton signUpjButton;
    private javax.swing.JLabel userNamejLabel;
    private javax.swing.JTextField userNamejTextField;
    // End of variables declaration//GEN-END:variables
    private boolean isUserExists(String userName) {
        try {
            java.io.File file = new java.io.File("resources/users.txtt");
            if (!file.exists()) {
                return false;
            }
            java.util.Scanner sc = new java.util.Scanner(file);
            while (sc.hasNextLine()) {
                String[] parts = sc.nextLine().split(":");
                if (parts[0].equals(userName)) {
                    return true;
                }
            }
        } catch (FileNotFoundException ex) {
        }
        return false;
    }

    private void saveUser(String userName, String password) {
        try {
            java.io.File file = new java.io.File("resources/users.txt");

            System.out.println("Saving to: " + file.getAbsolutePath());

            try (java.io.FileWriter writer = new java.io.FileWriter(file, true)) {
                writer.write(userName + ":" + password + "\n");
            }

        } catch (IOException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error saving user: " + ex.getMessage(), "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
}
